name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.697'

      - name: install dependencies
        run: npm install

      - name: build release
        run: clojure -M:dev:cljs-cli:patch release app

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./resources/public
