name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v1
        with:
          java-version: '21'

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 'latest'

      - name: install dependencies
        run: npm install

      - name: build release
        run: clojure -M:cljs-cli release app

      - name: Deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ./resources/public
